version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fax-backend
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./rag_corrections_db:/app/rag_corrections_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: fax-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --host-header=rewrite backend:8000
    depends_on:
      - backend
    ports:
      - "4040:4040" # ngrok inspector UI
